[project]
name = "operag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faiss-cpu>=1.12.0",
    "path>=17.1.1",
    "sentence-transformers>=5.1.1",
]
